# Generated by Django 2.0.5 on 2018-06-06 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_auto_20180604_0042'),
        ('activity', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='merchant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='merchant.Merchant'),
            preserve_default=False,
        ),
    ]
