# Generated by Django 2.0.5 on 2018-05-23 06:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('system', '系统通知'), ('activity', '活动消息'), ('game', '互动消息'), ('friend', '好友消息')], max_length=16)),
                ('title', models.CharField(max_length=36)),
                ('priority', models.IntegerField(choices=[(0, '默认优先级'), (1, '一级优先级'), (2, '二级优先级'), (3, '三级优先级')])),
                ('sender', models.IntegerField(default=-1)),
                ('content', models.TextField(max_length=512)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
