# Generated by Django 2.0.5 on 2018-05-10 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('passwd', models.CharField(max_length=64)),
                ('nickname', models.CharField(max_length=16)),
                ('gender', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('avatar', models.URLField()),
                ('signature', models.CharField(default='', max_length=64)),
                ('info', models.TextField(default='{}')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2018, 5, 10, 13, 6, 8, 410835))),
            ],
        ),
    ]
