# Generated by Django 2.0.5 on 2018-05-10 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 10, 13, 38, 2, 686446)),
        ),
    ]
