# Generated by Django 2.0.5 on 2018-05-17 13:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180510_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='followees',
            field=models.ManyToManyField(related_name='_user_followees_+', to='user.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='_user_followers_+', to='user.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('boy', '男'), ('girl', '女')], max_length=8),
        ),
        migrations.AddField(
            model_name='friendship',
            name='main_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_friendships', to='user.User'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='sub_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_friendships', to='user.User'),
        ),
    ]
