# Generated by Django 2.0.5 on 2018-05-17 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180517_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('nickname', models.CharField(max_length=16)),
                ('gender', models.CharField(choices=[('boy', '男'), ('girl', '女')], max_length=8)),
                ('avatar', models.URLField()),
                ('signature', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('nickname', models.CharField(max_length=16)),
                ('gender', models.CharField(choices=[('boy', '男'), ('girl', '女')], max_length=8)),
                ('avatar', models.URLField()),
                ('signature', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='followees',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.AddField(
            model_name='follower',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='user.User'),
        ),
        migrations.AddField(
            model_name='followee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followees', to='user.User'),
        ),
    ]
