# Generated by Django 2.0.5 on 2018-06-18 07:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180604_0042'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='game',
            name='initiator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='initiated_games', to='user.User'),
        ),
        migrations.AddField(
            model_name='game',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='participants',
            field=models.ManyToManyField(related_name='participated_games', to='user.User'),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('not_start', '还未开始'), ('in_progress', '正在进行'), ('finished', '已经结束')], default='not_start', max_length=16),
        ),
    ]
