# Generated by Django 2.0.5 on 2018-06-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20180619_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='type',
            field=models.CharField(choices=[('indoor', '室内'), ('outdoor', '室外'), ('online', '线上')], default='indoor', max_length=16),
        ),
    ]
